database:
  # uri: "mssql+pyodbc://anastasiia@server-labs :Password1!@server-clouds.database.windows.net:1433/db-sports?driver=ODBC+Driver+18+for+SQL+Server&Encrypt=yes&TrustServerCertificate=no&Connection Timeout=30"
  uri: "mysql://root:1234@127.0.0.1:3306/database"
