database:
  uri: "mssql+pyodbc://anastasiia%40server-clouds:Password1%21@server-clouds.database.windows.net:1433/db-sports?driver=ODBC+Driver+18+for+SQL+Server&Encrypt=yes&TrustServerCertificate=no&Connection Timeout=30"
